src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/TeacherController.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/classroom/service/TeacherService.java, src/main/java/com/sparta/finalproject/domain/gallery/controller/ImagePostController.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java, src/main/java/com/sparta/finalproject/global/dto/GlobalResponseDto.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java, src/main/java/com/sparta/finalproject/global/response/GlobalExceptionHandler.java, src/main/java/com/sparta/finalproject/global/response/exceptionType/ClassroomException.java, src/main/java/com/sparta/finalproject/global/response/exceptionType/GlobalException.java, src/main/java/com/sparta/finalproject/global/response/exceptionType/ImagePostException.java, src/main/java/com/sparta/finalproject/global/response/exceptionType/S3Exception.java, src/main/java/com/sparta/finalproject/global/response/exceptionType/UserException.java, src/main/java/com/sparta/finalproject/infra/s3/S3Service.java
=> Feat: 글로벌 예외 처리 구현

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/entity/Child.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
아이 프로필 조회는 추후 부모 Entity 생성되면 추가 필요
=> Feat: CRUD 아이 기능 추가

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/entity/Child.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/ClassroomResponseDto.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/TeacherRequestDto.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/TeacherResponseDto.java, src/main/java/com/sparta/finalproject/domain/classroom/entity/Teacher.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/gallery/dto/ImagePostResponseDto.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java, src/main/java/com/sparta/finalproject/global/response/GlobalExceptionHandler.java, src/main/java/com/sparta/finalproject/global/response/exceptionType/ChildException.java, src/main/java/com/sparta/finalproject/infra/s3/S3Service.java
=> Refactor: 변경된 ERD에 맞게 변수 수정, request resopnse를 객체를 반환하도록 변경, 시간 관련 클래스 패턴 수정

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/TeacherController.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/classroom/service/TeacherService.java, src/main/java/com/sparta/finalproject/domain/gallery/controller/ImagePostController.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Style: 메서드명과 statusCode를 컨벤션에 맞게 변경

src/main/java/com/sparta/finalproject/domain/child/entity/Child.java, src/main/java/com/sparta/finalproject/domain/gallery/repository/ImageRepository.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java, src/main/java/com/sparta/finalproject/global/config/CorsConfiguration.java
=> Feat:  임시로 cors 허용

src/main/java/com/sparta/finalproject/FinalProjectApplication.java, src/main/java/com/sparta/finalproject/domain/attendance/controller/AttendanceController.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/AbsentResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/EnterResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/ExitResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/entity/Attendance.java, src/main/java/com/sparta/finalproject/domain/attendance/repository/AttendanceRepository.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/global/config/WebConfig.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat: 등원, 하원, 결석 처리 / 취소 기능 구현

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/TeacherController.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/TeacherRequestDto.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/TeacherResponseDto.java, src/main/java/com/sparta/finalproject/domain/classroom/entity/Teacher.java, src/main/java/com/sparta/finalproject/domain/classroom/service/TeacherService.java, src/main/java/com/sparta/finalproject/domain/gallery/controller/ImagePostController.java, src/main/java/com/sparta/finalproject/domain/gallery/dto/ImagePostRequestDto.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java, src/main/java/com/sparta/finalproject/global/enumType/Gender.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java, src/main/java/com/sparta/finalproject/infra/s3/S3Service.java
=> Refactor: 이미지 관련 요청을 RequestPart에서 ModelAttribute로 변경

.github/workflows/cr.yml
=> Test: github action Gpt code-review test

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildrenEnterResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildrenExitResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ClassroomChildrenResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ManagerPageResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/entity/Child.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/ClassroomResponseDto.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/gallery/controller/ImagePostController.java, src/main/java/com/sparta/finalproject/domain/gallery/dto/GalleryPageResponseDto.java, src/main/java/com/sparta/finalproject/domain/gallery/repository/ImagePostRepository.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java
=> Refactor: 페이지네이션으로 반환되는 페이지에서 조건에 맞는 총 객체 갯수 함께 반환하도록 변경

build.gradle
=> #15 Fix : spring security가 improt 되자 않던 오류 수정

src/main/java/com/sparta/finalproject/FinalProjectApplication.java, src/main/java/com/sparta/finalproject/domain/attendance/repository/AttendanceRepository.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/global/procedure/MyCommandLineRunner.java, src/main/java/com/sparta/finalproject/global/procedure/MyStoredProcService.java, src/main/resources/import.sql
=> Refactor: 더미 데이터 생성, entity의 속성이 변경됨에 따른 쿼리 메서드 변경

src/main/java/com/sparta/finalproject/domain/gallery/controller/ImagePostController.java, src/main/java/com/sparta/finalproject/domain/gallery/entity/ImagePost.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Refactor: 사진 게시글 수정 기능 추가, 권한 검증 로직 추가

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/entity/Child.java, src/main/java/com/sparta/finalproject/domain/child/entity/ScheduleType.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> test: 챗지피티 코드 리뷰 테스트, 줄 정렬 커밋

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildScheduleRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Refactor : 관리자 페이지 조회 url 수정

src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Refactor : 시간 조회를 null 에서 전체시간으로 변경

src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/ClassroomResponseDto.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/ClassroomTeacherResponseDto.java, src/main/java/com/sparta/finalproject/domain/classroom/entity/Classroom.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/config/WebSecurityConfig.java, src/main/java/com/sparta/finalproject/domain/user/controller/UserController.java, src/main/java/com/sparta/finalproject/domain/user/dto/TeacherResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/repository/UserRepository.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat: 담임 선생님 기능 구현

src/main/java/com/sparta/finalproject/domain/attendance/controller/AttendanceController.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/DayAttendanceResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/MonthAttendanceResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/entity/Attendance.java, src/main/java/com/sparta/finalproject/domain/attendance/repository/AttendanceRepository.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildScheduleRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildScheduleResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepositoryImpl.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/global/enumType/AbsentReason.java, src/main/java/com/sparta/finalproject/global/enumType/AttendanceStatus.java, src/main/java/com/sparta/finalproject/global/enumType/CommuteStatus.java, src/main/java/com/sparta/finalproject/global/enumType/Day.java, src/main/java/com/sparta/finalproject/global/enumType/Status.java, src/main/java/com/sparta/finalproject/global/enumType/UserRoleEnum.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat : 해당반의 월별 출결 내역 조회 기능 추가 #75

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/entity/Child.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/config/WebSecurityConfig.java, src/main/java/com/sparta/finalproject/domain/user/controller/UserController.java, src/main/java/com/sparta/finalproject/domain/user/dto/ParentResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/entity/User.java, src/main/java/com/sparta/finalproject/domain/user/repository/UserRepository.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java, src/test/java/com/sparta/finalproject/controller/ChildControllerTest.java
부모 관련 기능 추가
Resolves:
Ref: #77 #78 #79 #80 #80
- 특이사항1 : X
=> Feat: 아이와 부모 관련 기능 추가

src/main/java/com/sparta/finalproject/domain/attendance/controller/AttendanceController.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/DateAttendanceResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat : 반 별 해당 날짜의 출결 내역 조회 기능 구현 #83

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/user/dto/ParentListResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/dto/ParentProfileResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/dto/ParentResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java
> Ref: #77 #78 #79 #80 #81
- 특이사항1
=> Feat: 아이와 부모 관련 기능 변경 및 삭제

src/main/java/com/sparta/finalproject/domain/attendance/entity/Attendance.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Feat : 스케쥴러를 사용한 토요일 출결 컬럼 생성, 매일 23시 59분에 자동 출결 기능 추가

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildAttendanceTimeResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat : 아이 등하원 시간 조회 기능 추가(학부모) #93

build.gradle, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/entity/Classroom.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/kindergarten/controller/KindergartenController.java, src/main/java/com/sparta/finalproject/domain/kindergarten/dto/KindergartenRequestDto.java, src/main/java/com/sparta/finalproject/domain/kindergarten/entity/Kindergarten.java, src/main/java/com/sparta/finalproject/domain/kindergarten/repository/KindergartenRepository.java, src/main/java/com/sparta/finalproject/domain/kindergarten/service/KindergartenService.java, src/main/java/com/sparta/finalproject/domain/user/controller/UserController.java, src/main/java/com/sparta/finalproject/domain/user/dto/ParentModifyRequestDto.java, src/main/java/com/sparta/finalproject/domain/user/dto/PrincipalModifyRequestDto.java, src/main/java/com/sparta/finalproject/domain/user/dto/PrincipalModifyResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/dto/TeacherModifyRequestDto.java, src/main/java/com/sparta/finalproject/domain/user/entity/User.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/enumType/UserRoleEnum.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java, src/main/java/com/sparta/finalproject/global/response/GlobalExceptionHandler.java, src/main/java/com/sparta/finalproject/global/response/exceptionType/KindergartenException.java
=> Feat: 유치원 엔티티 추가

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildProfileResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/dto/ChildResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/entity/Child.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Fix : 학부모 페이지 아이 수정 및 조회 기능 추가

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java, src/main/java/com/sparta/finalproject/domain/kindergarten/controller/KindergartenController.java, src/main/java/com/sparta/finalproject/domain/kindergarten/dto/KindergartenResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/dto/ParentModifyRequestDto.java, src/main/java/com/sparta/finalproject/domain/user/entity/User.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java
=> Refactor: 메서드 허용 권한 범주에 원장 선생님 추가

src/main/java/com/sparta/finalproject/domain/user/dto/UserResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> #15 Feat : 재로그인시 승인 대기중 상태를 반환

src/main/java/com/sparta/finalproject/domain/attendance/controller/AttendanceController.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/AbsentInfoDto.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/ChildMonthResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/ContentDto.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/InfoDto.java, src/main/java/com/sparta/finalproject/domain/attendance/repository/AbsentInfoRepository.java, src/main/java/com/sparta/finalproject/domain/attendance/repository/AttendanceRepository.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat : 자녀의 월별 출결 내역 조회 구현 #106

src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/kindergarten/dto/KindergartenResponseDto.java, src/main/java/com/sparta/finalproject/domain/kindergarten/service/KindergartenService.java, src/main/java/com/sparta/finalproject/domain/user/controller/UserController.java, src/main/java/com/sparta/finalproject/domain/user/dto/PrincipalProfileResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/dto/UserInfoResponseDto.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Refactor: 사이드바 조회 시 유치원 로고와 이름을 같이 반환하도록 변경

src/main/java/com/sparta/finalproject/domain/attendance/controller/AttendanceController.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/DefaultMessageDto.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/attendance/service/CustomMessageService.java, src/main/java/com/sparta/finalproject/domain/attendance/service/HttpCallService.java, src/main/java/com/sparta/finalproject/domain/attendance/service/MessageService.java, src/main/java/com/sparta/finalproject/domain/user/entity/User.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat : 카카오 알림 기능 추가 #51

src/main/java/com/sparta/finalproject/domain/attendance/repository/AttendanceRepository.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java
=> Feat : 월별 출결내역에서 count의 기준을 어제까지로하는 로직 추가 #75

src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/attendance/service/CustomMessageService.java, src/main/java/com/sparta/finalproject/domain/attendance/service/MessageService.java
=> Fix : 등원 알림 메시지에서 하원 시간 값에 null들어가는 에러 해결 #51

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Fix : 이미지가 안 들어오는 코드 수정

src/main/java/com/sparta/finalproject/domain/child/dto/SidebarChildrenInfo.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/response/GlobalExceptionHandler.java
=> Feat : 사이드바 정보 조회시 학부모님일 때 아이정보도 추가하기

src/main/java/com/sparta/finalproject/domain/attendance/service/CustomMessageService.java
=> Feat : 알림 메세지에서 바로가기 버튼 url 연결 #51

src/main/java/com/sparta/finalproject/domain/attendance/service/CustomMessageService.java
=> Refactor : 카카오 알림 메시지 텍스트 에러 해결

src/main/java/com/sparta/finalproject/domain/child/dto/ChildRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Feat : 아이 프로필 수정에서 기본 이미지로 변경 가능하게 추가

src/main/java/com/sparta/finalproject/domain/attendance/repository/AttendanceRepository.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java
=> Refactor : 월별 출결 내역 조회를 오늘까지 보이도록 수정 #75

build.gradle, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/kindergarten/service/KindergartenService.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/infra/s3/AwsS3Service.java, src/main/java/com/sparta/finalproject/infra/s3/CustomMultipartFile.java
=> Feat: 이미지 리사이징 구현

src/main/java/com/sparta/finalproject/domain/attendance/service/CustomMessageService.java
=> Fix : 카카오톡 알림 메시지 에러 해결 #51

src/main/java/com/sparta/finalproject/domain/api/controller/AirContorller.java, src/main/java/com/sparta/finalproject/domain/api/entity/AirQuality.java, src/main/java/com/sparta/finalproject/domain/api/service/AirService.java
Resolves:
Ref: #126
- 특이사항1
- 특이사항2
=> Feat : 서울시 미세먼지 API

src/main/java/com/sparta/finalproject/domain/attendance/entity/Attendance.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Fix : 주말에 아이 등록시 등하원 관리 탭에서 보이는 오류 해결 #67

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/gallery/controller/ImagePostController.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java, src/main/java/com/sparta/finalproject/domain/user/controller/UserController.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java
=> Refactor : url 수정 #133

src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/dto/ClassroomResponseDto.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java
=> Refactor : response Dto에 모든 반 정보 추가 #73

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/dto/CustomPageImpl.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepositoryCustom.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepositoryImpl.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Refactor : response Dto에 모든 반 정보 추가 #67

src/main/java/com/sparta/finalproject/domain/attendance/controller/AttendanceController.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/MonthAttendanceDto.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/MonthAttendanceResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java
=> Refactor : response Dto에 모든 반 정보 추가 #75

src/main/java/com/sparta/finalproject/domain/classroom/repository/ClassroomRepository.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java
=> Refactor : 반별 페이지 조회에서 default -1 #73

src/main/java/com/sparta/finalproject/domain/attendance/controller/AttendanceController.java, src/main/java/com/sparta/finalproject/domain/attendance/dto/DateResponseDto.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java
=> Refactor : -1을 반환받을 시 id값이 가장 작은 classroom 조회되도록 수정 #83

src/main/java/com/sparta/finalproject/domain/child/dto/ChildResponseDto.java, src/main/java/com/sparta/finalproject/domain/child/entity/Child.java
=> Fix : 아이 생성시 등/하원 추가

src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/child/entity/Child.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/entity/Classroom.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/gallery/entity/ImagePost.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat : 반 삭제 기능 구현 #131

src/main/java/com/sparta/finalproject/domain/kindergarten/dto/KindergartenRequestDto.java, src/main/java/com/sparta/finalproject/domain/kindergarten/service/KindergartenService.java
=> Refactor : 로고 이미지 받는 로직 수정

src/main/java/com/sparta/finalproject/domain/jwt/AccessTokenReissuanceController.java, src/main/java/com/sparta/finalproject/domain/user/controller/UserController.java, src/main/java/com/sparta/finalproject/domain/user/entity/User.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> Feat : 회원탈퇴(카카오 연결 끊기 + DB 데이터 삭제)

src/main/java/com/sparta/finalproject/domain/child/dto/ChildRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Refactor : 아이 이미지 수정 관련 에러 처리

src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepository.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepositoryCustom.java, src/main/java/com/sparta/finalproject/domain/child/repository/ChildRepositoryImpl.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java
=> Feature/아이 등하원 현황 조회

build.gradle, src/main/java/com/sparta/finalproject/domain/child/dto/ChildRequestDto.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/user/dto/CommonGetProfileImageRequestDto.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/resources/import.sql
=> Fix: isCancelled String 타입으로 변경

build.gradle, src/main/java/com/sparta/finalproject/domain/config/WebSecurityConfig.java, src/main/java/com/sparta/finalproject/domain/gallery/entity/Image.java, src/main/java/com/sparta/finalproject/domain/gallery/entity/ImagePost.java, src/main/java/com/sparta/finalproject/domain/jwt/AccessTokenReissuanceController.java, src/main/java/com/sparta/finalproject/domain/jwt/AccessTokenReissuanceService.java, src/main/java/com/sparta/finalproject/domain/jwt/JwtAuthFilter.java, src/main/java/com/sparta/finalproject/domain/jwt/JwtUtil.java, src/main/java/com/sparta/finalproject/domain/jwt/RefreshToken.java, src/main/java/com/sparta/finalproject/domain/jwt/RefreshTokenRepository.java, src/main/java/com/sparta/finalproject/domain/security/CustomAuthenticationEntryPoint.java, src/main/java/com/sparta/finalproject/domain/user/controller/UserController.java, src/main/java/com/sparta/finalproject/domain/user/entity/User.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java, src/main/java/com/sparta/finalproject/infra/s3/S3Service.java
=> Refactor : 프로젝트 전체적으로 수정 및 개선 사항 반영

src/main/java/com/sparta/finalproject/domain/api/controller/AirController.java, src/main/java/com/sparta/finalproject/domain/api/entity/RealtimeCityAir.java, src/main/java/com/sparta/finalproject/domain/api/entity/Row.java, src/main/java/com/sparta/finalproject/domain/api/service/AirService.java
=> Refactor : 코드리팩토링

src/main/java/com/sparta/finalproject/domain/air/controller/AirController.java, src/main/java/com/sparta/finalproject/domain/air/entity/RealtimeCityAir.java, src/main/java/com/sparta/finalproject/domain/air/entity/Row.java, src/main/java/com/sparta/finalproject/domain/air/service/AirService.java, src/main/java/com/sparta/finalproject/domain/attendance/service/AttendanceService.java, src/main/java/com/sparta/finalproject/domain/child/controller/ChildController.java, src/main/java/com/sparta/finalproject/domain/child/service/ChildService.java, src/main/java/com/sparta/finalproject/domain/classroom/controller/ClassroomController.java, src/main/java/com/sparta/finalproject/domain/classroom/service/ClassroomService.java, src/main/java/com/sparta/finalproject/domain/gallery/controller/ImagePostController.java, src/main/java/com/sparta/finalproject/domain/gallery/service/ImagePostService.java, src/main/java/com/sparta/finalproject/domain/kindergarten/controller/KindergartenController.java, src/main/java/com/sparta/finalproject/domain/user/controller/UserController.java, src/main/java/com/sparta/finalproject/domain/user/service/UserService.java, src/main/java/com/sparta/finalproject/global/config/AppConfig.java, src/main/java/com/sparta/finalproject/global/config/WebSecurityConfig.java, src/main/java/com/sparta/finalproject/global/config/jwt/JwtAuthFilter.java, src/main/java/com/sparta/finalproject/global/config/jwt/JwtUtil.java, src/main/java/com/sparta/finalproject/global/config/refreshToken/AccessTokenReissuanceController.java, src/main/java/com/sparta/finalproject/global/config/refreshToken/AccessTokenReissuanceService.java, src/main/java/com/sparta/finalproject/global/config/refreshToken/RefreshToken.java, src/main/java/com/sparta/finalproject/global/config/refreshToken/RefreshTokenRepository.java, src/main/java/com/sparta/finalproject/global/response/CustomStatusCode.java
=> refactor: 불필요한 코드 제거 및 주석 추가, 패키지 구조 및 메서드 명 변경
